export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

export const GET_USERS = "GET_USERS";
export const USERS_ERROR = "USERS_ERROR";
export const ADD_SHARED = "ADD_SHARED";
export const REMOVE_SHARED = "REMOVE_SHARED";
export const GET_SHARED = "GET_SHARED";

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const PACIENTE_AGREGADO = 'PACIENTE_AGREGADO';
export const PACIENTE_MODIFICADO = 'PACIENTE_MODIFICADO';
export const PACIENTE_ELIMINADO = 'PACIENTE_ELIMINADO';
export const AGREGAR_PACIENTE = 'AGREGAR_PACIENTE';
export const MODIFICAR_PACIENTE = 'MODIFICAR_PACIENTE';
export const ELIMINAR_PACIENTE = 'ELIMINAR_PACIENTE';
export const DETALLES_PACIENTE = 'DETALLES_PACIENTE';
export const SEGUIMIENTO_PACIENTE = 'SEGUIMIENTO_PACIENTE';
export const AGREGAR_SEGUIMIENTO = 'AGREGAR_SEGUIMIENTO';
export const MODIFICAR_SEGUIMIENTO = 'MODIFICAR_SEGUIMIENTO';
export const PACIENTES_CARGADOS = 'PACIENTES_CARGADOS';
export const PACIENTE_ERROR = 'PACIENTE_ERROR';
export const PACIENTE_BUSQUEDA = 'PACIENTE_BUSQUEDA';
export const PACIENTES_INIT = 'PACIENTES_INIT';
export const LISTAR_PACIENTES = 'LISTAR_PACIENTES';

export const PACIENTE_AGREGADO_EPF = "PACIENTE_AGREGADO_EPF";

export const RECETA_AGREGADA = "RECETA_AGREGADA";
export const RECETA_ELIMINADA = "RECETA_ELIMINADA";
export const RECETA_ERROR = "RECETA_ERROR";
export const RECETA_DETALLES = "RECETA_DETALLES";

export const UPDATE_RECETAS = "UPDATE_RECETAS";
export const UPDATE_RECETAS_ERROR = "UPDATE_RECETAS_ERROR";
